### ISSUE TITLE
Components collection registration

### ISSUE THREAD

**Issue by miljan-aleksic** [pablohpsilva/vuejs-component-style-guide#11]
I am rising this ticket to discuss about a best practice for the below, and if results of interest add it as a style guide.

A collection of components can be registered globally or locally as required. Both would have the same output but there are different implications.

## Global approach

Is easier to use, set it once and use as required. It will bloat the code, as the entire library get installed. Seem good approach for prototyping, tests, etc.

```js
import Vue from 'vue'
import MyLibrary from 'my-library'

Vue.install(MyLibrary)
```
```js
export default {
  template: '<my-lib-button></my-lib-button>'
}
```

## Local approach

You only import what you use making it possible to take advantage of tree-shaking.

```js
import Button from 'my-library/lib/button'

export default {
  components: { 'MyButton': Button },
  template: '<my-button></my-button>'
}
```

**Comment by Elfayer** [comment]
It looks more like a documentation ("how to") rather than a guide ("best practice ") to me. I think if talking about `render` functions, the most important thing is to know when to use it.

**Comment by miljan-aleksic** [comment]
@Elfayer, from the above which approach would you take and why?

**Comment by Elfayer** [comment]
That's the thing. To me choosing between a global or local component is not `render` function related.
It is a global component if you should access it from anywhere.

**Comment by miljan-aleksic** [comment]
@Elfayer, you are right, the local components could be used in a template as well. I have reformulated the issue.

**Comment by pablohpsilva** [comment]
Hello @miljan-aleksic and @Elfayer ! :D 

In my opinion: it really depend. To answer that question I would at least consider if the component I wanna have on global scope is used over and over again during my application.

Generally speaking? I would choose the local over the global approach. Why? Because, in general, the components I create/use are not global needed. 

It really depends on the developer to know when to use global/local components. As a rule of thumb: If a component is being used over and over again in several parts of the application, it should be placed on global scope.

**Edit**:
The apps I'm working on I've a specific directory called `shared-components`. That's where I save all sharable components used in my application. As a rule of thumb, if the component is being used two or more times in different pages/components in my app, it should be moved to that directory. So far, there was no need of placing components on global scope.

**Comment by pablohpsilva** [comment]
Since there was no further discussion, I'm closing this issue for now.
