### ISSUE TITLE
Assign this to component

### ISSUE THREAD

**Issue by xralphack** [pablohpsilva/vuejs-component-style-guide#16]
Can you tell more about this topic? I am confused how to implement this instead of using const self = this

**Comment by pablohpsilva** [comment]
Hello @xralphack ! Thank you for this issue :D 

Its quite simple: Since the ECMAScript 6 was launched, when using it, there's no need for binding a variable to `this`. All you have to do is write functions in ES6 format and binding the `this` to a `self` variable will not be needed.

Example:

```javascript
export default {
  methods: {
    sayHello() { ... },
    test() { // function in ES6
      this.somePromisse().then(() => { this.sayHello(); }); // it will work.
    },
  },
};
```
For more information, please, read [this](http://es6-features.org/#Lexicalthis).

**Comment by xralphack** [comment]
Got it. Thanks for your explanation!

**Comment by pablohpsilva** [comment]
You're welcome @xralphack :D
